<a href="https://colab.research.google.com/github/Anneshabhakta2005/Machine-Learning/blob/main/Numpy_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello")

Hello


In [ ]:
import numpy as np
a=np.arange(12)

print(a)
print("Last Element:",a[-1])
print("Dimension of a",a.ndim)
print("Shape of a:",a.shape)
print("Data typeof each element:",a.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Last Element: 11
Dimension of a 1
Shape of a: (12,)
Data typeof each element: int64


In [ ]:
print(a)
print("####################")
b=a.reshape(3,4)
print(b)
print("dimension of b:",b.ndim)
print("Sum of all:",b.sum())
print("Average of all:",b.mean())
print("Row Sum:",b.sum(axis=1))
print("Column sum:",b.sum(axis=0))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
####################
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
dimension of b: 2
Sum of all: 66
Average of all: 5.5
Row Sum: [ 6 22 38]
Column sum: [12 15 18 21]


In [ ]:
print(b)
print("################")
print(np.ravel(b))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
################
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
m=np.array([[1,2],[3,4]])
print(m)
c=m*3
print("###############")
print(c)
print(m>3)

[[1 2]
 [3 4]]
###############
[[ 3  6]
 [ 9 12]]
[[False False]
 [False  True]]


In [ ]:
print(m)
print("#####################")
n=np.array([[5,6],[7,8]])
print(n)
print("###########")
print(m*n)
print("###########")
print(m.dot(n))

[[1 2]
 [3 4]]
#####################
[[5 6]
 [7 8]]
###########
[[ 5 12]
 [21 32]]
###########
[[19 22]
 [43 50]]


In [ ]:
np.sqrt(289)

np.float64(17.0)

In [ ]:
k1=np.zeros((3,4))
k1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
import pandas as pd
s1=pd.Series([11,22,33,44])
print(s1)
s2=pd.Series([11,22,33,44],index=['a','b','c','d'])

0    11
1    22
2    33
3    44
dtype: int64


In [ ]:
d1={"id":101,"name":"Raj","age":21}
s3=pd.Series(d1)
print(s3)

NameError: name 'pd' is not defined

In [ ]:
d2={
    "names":[""]
}